# Generated by Django 4.2.11 on 2024-04-18 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorista', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalControleVeiculo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de criação')),
                ('data_modificacao', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de modificação')),
                ('origem_dados', models.IntegerField(blank=True, choices=[(1, 'Manual'), (2, 'Importado'), (3, 'Sistema')], default=1, null=True, verbose_name='Origem dos dados')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_saida', models.DateField(verbose_name='Data da saída')),
                ('hora_saida', models.TimeField(verbose_name='Hora da saída')),
                ('km_saida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Km da saída')),
                ('destino', models.CharField(blank=True, max_length=300, null=True, verbose_name='Destino')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data do retorno')),
                ('hora_retorno', models.TimeField(blank=True, null=True, verbose_name='Hora da chegada')),
                ('km_retorno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Km da volta')),
                ('km_percorrido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Km percorridos')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='motorista.motorista', verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='veiculo.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'historical Controle do veículo',
                'verbose_name_plural': 'historical Controle dos veículos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ControleVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de modificação')),
                ('origem_dados', models.IntegerField(blank=True, choices=[(1, 'Manual'), (2, 'Importado'), (3, 'Sistema')], default=1, null=True, verbose_name='Origem dos dados')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_saida', models.DateField(verbose_name='Data da saída')),
                ('hora_saida', models.TimeField(verbose_name='Hora da saída')),
                ('km_saida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Km da saída')),
                ('destino', models.CharField(blank=True, max_length=300, null=True, verbose_name='Destino')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data do retorno')),
                ('hora_retorno', models.TimeField(blank=True, null=True, verbose_name='Hora da chegada')),
                ('km_retorno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Km da volta')),
                ('km_percorrido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Km percorridos')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='motorista.motorista', verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='veiculo.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Controle do veículo',
                'verbose_name_plural': 'Controle dos veículos',
                'db_table': 'controle',
            },
        ),
    ]
