ORIGEM_DADO_MANUAL = 1
ORIGEM_DADO_IMPORTADO = 2
ORIGEM_DADO_SISTEMA = 3

CHOICE_ORIGEM_DADOS = (
    (ORIGEM_DADO_MANUAL, 'Manual'),
    (ORIGEM_DADO_IMPORTADO, 'Importado'),
    (ORIGEM_DADO_SISTEMA, 'Sistema'),
)
